### PR TITLE
Update from android 13.0.0_r2

### PR DESCRIPTION
**Pull request by xiaoxindada**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
why revert networkstack?
signapk libs doesn't need update?

**Comment by xiaoxindada** [comment]
> why revert networkstack? signapk libs doesn't need update?

It seems to work fine in my linux environment without updating the signapk libs.
networkstack doesn't seem to require additional links.

**Comment by erfanoabdi** [comment]
maybe its for backward compatibility for some "weird" android version
doesn't hurt to have that symlink anyway

**Comment by xiaoxindada** [comment]
> maybe its for backward compatibility for some "weird" android version doesn't hurt to have that symlink anyway

Okay

**Comment by erfanoabdi** [comment]
Thanks for your contribution

**Pull request merged**
